name: copiar tratativas para ec2
on:
  workflow_call:

jobs:      
  deploy-input-iot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          repository: 'Grupo-5-Projeto/Cloud'
          path: cloud

      - name: get credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ORG }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ORG }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN_ORG }}
          aws-region: ${{ secrets.AWS_REGION_ORG }}

      - name: get ec2 public ip
        run: |
          ls
          cd cloud
          ls
          EC2_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=arquitetura-upa-atualizada-sptech" --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
          echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV

      - name: key
        run: |
          cd tratativas-de-dados-atualizado /tratativas-de-dados-atualizado
          echo "${{ secrets.KEY_PEM_ORG }}" > urubu100-key.pem
          chmod 400 urubu100-key.pem

      - name: test
        run: |
          cd tratativas-de-dados-atualizado /tratativas-de-dados-atualizado 
          ls

      - name: copy tratativas archives to instace
        run: |
          cd tratativas-de-dados-atualizado /tratativas-de-dados-atualizado 
          scp -i ./urubu100-key.pem -o StrictHostKeyChecking=no ./tratativas-novas/{*,.*} ec2-user@${{env.EC2_IP}}:/home/ec2-user/tratativas
      


        
